name = "Anemos.jl"
uuid = "12bedb95-3428-4ce4-a3a4-f1281184f112"
authors = ["Zach Drake"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
